name: pokedex
description: A project to describe details of pokèmon.

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  dio: ^4.0.4
  dio_http_cache: ^0.3.0
  flutter_bloc: ^8.0.1
  flutter:
    sdk: flutter
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  json_annotation: ^4.1.0
  sliding_up_panel: ^2.0.0+1
  stream_transform: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  hive_generator: ^1.1.2
  json_serializable: ^4.1.4
  pedantic: ^1.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/items.json
    - assets/pokemons.json
    - assets/images/
 
  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Book.ttf

        - asset: assets/fonts/CircularStd-Medium.ttf
          weight: 600

        - asset: assets/fonts/CircularStd-Black.ttf
          weight: 700

        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 900